"""One axial cross-section comparison row."""
struct SectionComparisonRow
    case_label::String
    severity::Float64
    operator::String
    model::String
    nx::Int
    dt_s::Float64
    initial_condition::String
    backend::String
    run_status::String
    coordinate_mode::String
    z_cm::Float64
    area_cm2::Float64
    flow_3d_cm3_s::Float64
    flow_1d_cm3_s::Float64
    mean_u3d_cm_s::Float64
    mean_u1d_cm_s::Float64
    abs_velocity_error_cm_s::Float64
    flow_abs_error_cm3_s::Float64
    rel_error::Float64
    rel_l2_velocity_component::Float64
    intersection_count::Int
    area_valid::Bool
    cut_status::String
    node_count::Int
    observed_radius_cm::Float64
    xdmf_time_s::Float64
    time_error_s::Float64
    target_time_s::Float64
    time_atol_s::Float64
    one_d_completed_time_s::Float64
    one_d_terminal_time_error_s::Float64
    xdmf_target_time_error_s::Float64
    cross_model_time_offset_s::Float64
end

"""One area-weighted radial-bin profile comparison row."""
struct RadialProfileRow
    case_label::String
    severity::Float64
    operator::String
    model::String
    nx::Int
    dt_s::Float64
    initial_condition::String
    backend::String
    run_status::String
    coordinate_mode::String
    z_slice_cm::Float64
    radial_bin::Int
    r_over_r0_mid::Float64
    area_cm2::Float64
    flow_3d_cm3_s::Float64
    mean_u3d_cm_s::Float64
    mean_u1d_cm_s::Float64
    abs_velocity_error_cm_s::Float64
    rel_error::Float64
    intersection_count::Int
    area_valid::Bool
    node_count::Int
    xdmf_time_s::Float64
    time_error_s::Float64
    target_time_s::Float64
    time_atol_s::Float64
    one_d_completed_time_s::Float64
    one_d_terminal_time_error_s::Float64
    xdmf_target_time_error_s::Float64
    cross_model_time_offset_s::Float64
    radial_bin_count::Int
    radius_mode::String
    radius_scale_cm::Float64
    current_area_cm2::Float64
    reference_area_cm2::Float64
    current_area_mismatch_rel::Float64
    velocity_variance_cm2_s2::Float64
end

"""Supplemental node-slab sensitivity row."""
struct NodeSlabSensitivityRow
    case_label::String
    severity::Float64
    model::String
    nx::Int
    dt_s::Float64
    initial_condition::String
    backend::String
    run_status::String
    coordinate_mode::String
    half_width_cm::Float64
    z_cm::Float64
    mean_u3d_cm_s::Float64
    mean_u1d_cm_s::Float64
    abs_velocity_error_cm_s::Float64
    rel_error::Float64
    node_count::Int
    observed_radius_cm::Float64
    xdmf_time_s::Float64
    time_error_s::Float64
    target_time_s::Float64
    time_atol_s::Float64
    one_d_completed_time_s::Float64
    one_d_terminal_time_error_s::Float64
    xdmf_target_time_error_s::Float64
    cross_model_time_offset_s::Float64
end

"""Compact per-case comparison summary."""
struct ComparisonSummaryRow
    case_label::String
    severity::Float64
    operator::String
    model::String
    nx::Int
    dt_s::Float64
    initial_condition::String
    backend::String
    run_status::String
    coordinate_mode::String
    section_count::Int
    profile_count::Int
    mean_abs_error_cm_s::Float64
    l2_velocity_error_cm_s::Float64
    max_abs_error_cm_s::Float64
    mean_rel_error::Float64
    relative_l1_velocity_error::Float64
    max_rel_error::Float64
    rel_l2_velocity_error::Float64
    mean_flow_abs_error_cm3_s::Float64
    flow_l2_error_cm3_s::Float64
    max_flow_abs_error_cm3_s::Float64
    profile_mean_abs_error_cm_s::Float64
    profile_l2_error_cm_s::Float64
    profile_max_abs_error_cm_s::Float64
    min_intersection_count::Int
    min_section_nodes::Int
    area_valid_count::Int
    alpha_eff_min::Float64
    alpha_eff_max::Float64
    characteristic_radicand_min::Float64
    lambda_minus_min::Float64
    lambda_minus_max::Float64
    lambda_plus_min::Float64
    lambda_plus_max::Float64
    subcritical_margin_min::Float64
    accepted_dt_min::Float64
    accepted_dt_max::Float64
    realized_cfl_max::Float64
    min_solver_area::Float64
    min_physical_area_cm2::Float64
    solver_volume_defect::Float64
    physical_volume_defect_cm3::Float64
    positivity_projection_count::Int
    positivity_correction_total::Float64
    final_inlet_area_flux::Float64
    final_outlet_area_flux::Float64
    final_area_flux_balance::Float64
    final_rhs_area_max_abs::Float64
    final_rhs_flow_max_abs::Float64
    xdmf_time_s::Float64
    time_error_s::Float64
    target_time_s::Float64
    time_atol_s::Float64
    one_d_completed_time_s::Float64
    one_d_terminal_time_error_s::Float64
    xdmf_target_time_error_s::Float64
    cross_model_time_offset_s::Float64
end

"""Compact per-case, per-grid resolved-3D grid-sensitivity summary."""
struct GridSensitivitySummaryRow
    case_label::String
    severity::Float64
    operator::String
    model::String
    nx::Int
    dt_s::Float64
    initial_condition::String
    backend::String
    run_status::String
    coordinate_mode::String
    target_time_s::Float64
    section_count::Int
    valid_section_count::Int
    mean_physical_flow_bias_cm3_s::Float64
    mean_physical_flow_discrepancy_cm3_s::Float64
    rms_physical_flow_discrepancy_cm3_s::Float64
    mean_velocity_bias_cm_s::Float64
    mean_velocity_discrepancy_cm_s::Float64
    rms_velocity_discrepancy_cm_s::Float64
    max_velocity_discrepancy_cm_s::Float64
    max_velocity_discrepancy_z_cm::Float64
    relative_rms_velocity_discrepancy::Float64
    adjacent_from_nx::Int
    adjacent_mean_abs_velocity_difference_cm_s::Float64
    adjacent_rms_velocity_difference_cm_s::Float64
    adjacent_max_abs_velocity_difference_cm_s::Float64
    adjacent_relative_rms_velocity_difference::Float64
    one_d_completed_time_s::Float64
    cross_model_time_offset_s::Float64
    comparison_summary_csv::String
    section_csv::String
end

"""Return value from `run_comparison`."""
struct ComparisonResult{S<:ComparisonSpec}
    spec::S
    section_rows::Vector{SectionComparisonRow}
    profile_rows::Vector{RadialProfileRow}
    sensitivity_rows::Vector{NodeSlabSensitivityRow}
    summary_rows::Vector{ComparisonSummaryRow}
    section_csvs::Vector{String}
    profile_csvs::Vector{String}
    sensitivity_csv::String
    summary_csv::String
    svg_paths::Vector{String}
end

"""Return value from `run_grid_sensitivity`."""
struct GridSensitivityResult{S<:GridSensitivitySpec}
    spec::S
    comparison_results::Vector{ComparisonResult}
    summary_rows::Vector{GridSensitivitySummaryRow}
    summary_csv::String
    summary_tex::String
end
