include("resolved3d_compare_common.jl")
include("resolved3d_compare_observations.jl")
include("resolved3d_compare_rows.jl")
include("resolved3d_compare_runner.jl")
include("resolved3d_compare_grid_sensitivity.jl")
