const OPERATOR_VALIDATION_HEADER = [
    "validation_case",
    "z_cm",
    "shift_cm",
    "area_cm2",
    "expected_area_cm2",
    "area_abs_error_cm2",
    "flow_cm3_s",
    "expected_flow_cm3_s",
    "flow_abs_error_cm3_s",
    "mean_velocity_cm_s",
    "expected_mean_velocity_cm_s",
    "mean_abs_error_cm_s",
    "area_delta_cm2",
    "flow_delta_cm3_s",
    "mean_velocity_delta_cm_s",
    "intersection_count",
    "max_triangle_mean_error_cm_s",
    "cut_status",
    "status",
]

function write_operator_validation_csv(path::String, rows::Vector{OperatorValidationRow}; overwrite::Bool = false)
    return write_csv_table(path, OPERATOR_VALIDATION_HEADER, (operator_validation_csv_values(row) for row in rows); overwrite)
end

function operator_validation_csv_values(row::OperatorValidationRow)
    return Any[
        row.validation_case,
        row.z_cm,
        row.shift_cm,
        row.area_cm2,
        row.expected_area_cm2,
        row.area_abs_error_cm2,
        row.flow_cm3_s,
        row.expected_flow_cm3_s,
        row.flow_abs_error_cm3_s,
        row.mean_velocity_cm_s,
        row.expected_mean_velocity_cm_s,
        row.mean_abs_error_cm_s,
        row.area_delta_cm2,
        row.flow_delta_cm3_s,
        row.mean_velocity_delta_cm_s,
        row.intersection_count,
        row.max_triangle_mean_error_cm_s,
        row.cut_status,
        row.status,
    ]
end

"""
    write_operator_validation_tex(path, rows; overwrite=false)

Write the compact LaTeX summary table emitted by the operator-validation
workflow. The table reports only the bounded synthetic validation metrics used
by the workflow itself.
"""
function write_operator_validation_tex(path::String, rows::Vector{OperatorValidationRow}; overwrite::Bool = false)
    guarded_open_write(path, overwrite) do io
        println(io, "% Generated by run_operator_validation; input mesh and fields are synthetic.")
        println(io, "\\begin{tabular}{lrrrrrrrl}")
        println(io, "\\toprule")
        println(io, "case & z & shift & area & flow err. & mean err. & shift \$\\Delta A\$ & shift \$\\Delta \\bar u\$ & status \\\\")
        println(io, "\\midrule")
        for row in rows
            println(io, operator_validation_latex_row(row))
        end
        println(io, "\\bottomrule")
        println(io, "\\end{tabular}")
    end
    return path
end

function operator_validation_latex_row(row::OperatorValidationRow)
    return join(
        [
            replace(row.validation_case, "_" => "\\_"),
            latex_number(row.z_cm),
            latex_number(row.shift_cm),
            latex_number(row.area_cm2),
            latex_number(row.flow_abs_error_cm3_s),
            latex_number(row.mean_abs_error_cm_s),
            latex_number(row.area_delta_cm2),
            latex_number(row.mean_velocity_delta_cm_s),
            row.status,
        ],
        " & ",
    ) * " \\\\"
end
