include("operator_validation_types.jl")
include("operator_validation_synthetic.jl")
include("operator_validation_metrics.jl")
include("operator_validation_outputs.jl")
include("operator_validation_runner.jl")
